default_language_version:
    python: python3.12.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--line-length=88]
        language_version: python3.12.11
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0 # Or the latest stable version
    hooks:
    -   id: flake8
